repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: local
    hooks:
      - id: flutter-analyze
        name: flutter analyze
        entry: flutter
        args: [analyze]
        language: system
        pass_filenames: false

      - id: flutter-test
        name: flutter test
        entry: flutter
        args: [test]
        language: system
        pass_filenames: false

      - id: dart-format
        name: dart format
        entry: dart
        args: [format, --output=none, --set-exit-if-changed, .]
        language: system
        pass_filenames: false
