name: github_finder_flutter
description: A Flutter app to search GitHub repositories.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  flutter_lints: ^4.0.0
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
